### ISSUE TITLE
some PR are stalled

### ISSUE THREAD

**Issue by doradsoft** [bible-on-site/bible-on-site#22]
#21 I.E. cannot be merged as some requirements are not met, but they were never triggered,, probably because the change was from outside ./web/bible-on-site

**Comment by HagegeR** [comment]
it's a part of your request to not have PR run on simple non code related changes
but at the same time we want PRs to have required build before merging
I'm not sure how to reconcile both requests just yet

**Comment by doradsoft** [comment]
Indeed, you'll find a way I'm sure :-)

**Comment by HagegeR** [comment]
fixed with #26
