### ISSUE TITLE
calculate coverage and place withing a badge

### ISSUE THREAD

**Issue by doradsoft** [bible-on-site/bible-on-site#3]
find a way to merge coverage reports from unit (jest) + e2e/perf (playwright)

**Comment by HagegeR** [comment]
You want the coverage badge to be a mean of the results from two languages, is that correct?

**Comment by doradsoft** [comment]
Negative, All code under test is currently in `ts` but there are different testing framework. Jest for unit/integration and playwright for e2e/performance. So each are run separately and produces different coverage report file.
So need to merge (more like accumulate than average, but not precisely as the might be intersections). It's considered a common task (even if not trivial one).
Some references:
https://dev.to/szmydlo/comprehensive-coverage-jestplaywright-in-nextjs-ts-1df2
https://github.com/selfagency/merge-coverage

**Comment by HagegeR** [comment]
maybe you could add a readme and I'll insert the coverage bade into it when ready?

**Comment by HagegeR** [comment]
when you'll have time look if #7 fixed this

**Comment by doradsoft** [comment]
Made much more progress in `coverage` branch.
e2e and perf are now generating coverage reports into `coverage/(e2e|perf)`.
Tasks:

- [X] Playwright coverage (hard task)
- [ ] Jest coverage (easy task)
- [ ] populate coverage for files that weren't touched at all
- [ ]  Merge coverage (https://www.npmjs.com/package/monocart-coverage-reports#merge-coverage-reports:~:text=and%20merging%20reports-,Manual%20Merging,-If%20the%20reports)

**Comment by doradsoft** [comment]
- [X] Jest coverage (easy task)

Jest coverage is done as well. Sorry I resolved the conflict in a bit violence due to a rush. Will be in touch on how to utilize Codecov with new infra.

**Comment by doradsoft** [comment]
forgot to say that:
- [X] populate coverage for files that weren't touched at all
was resolved as well. Just that it was resolved for Jest only, which make it only valuable when merging, which is sufficient for now.

Now working on local merging.

**Comment by HagegeR** [comment]
Separating the coverage collection process from your main test run can be a good way to isolate issues and potentially improve performance. Here are a few ways to implement this approach:

1. Use a separate script for coverage collection:

   Create a new script in your `package.json`:

   ```json
   {
     "scripts": {
       "test:e2e": "playwright test --config=playwright.e2e.config.ts",
       "collect-coverage": "node collect-coverage.js"
     }
   }
   ```

   Then create a `collect-coverage.js` file:

   ```javascript
   const { chromium } = require('playwright');
   const fs = require('fs');

   (async () => {
     const browser = await chromium.launch();
     const context = await browser.newContext();
     const page = await context.newPage();
     
     await page.coverage.startJSCoverage();
     await page.goto('http://your-app-url');
     // Perform any necessary interactions
     const coverage = await page.coverage.stopJSCoverage();
     
     await browser.close();

     fs.writeFileSync('coverage.json', JSON.stringify(coverage));
   })();
   ```

   Run these scripts separately in your CI pipeline.

2. Use a post-test hook:

   Modify your Playwright config to run a script after tests complete:

   ```typescript
   // playwright.e2e.config.ts
   import type { PlaywrightTestConfig } from '@playwright/test';

   const config: PlaywrightTestConfig = {
     // ... other config options
     globalTeardown: require.resolve('./collect-coverage'),
   };

   export default config;
   ```

   Then in `collect-coverage.ts`:

   ```typescript
   import fs from 'fs';
   import path from 'path';

   async function globalTeardown() {
     const coverageDir = path.join(__dirname, 'coverage');
     if (!fs.existsSync(coverageDir)) {
       fs.mkdirSync(coverageDir);
     }

     const coverageFiles = fs.readdirSync(process.cwd())
       .filter(file => file.endsWith('.coverage.json'));

     coverageFiles.forEach(file => {
       const content = fs.readFileSync(file, 'utf8');
       fs.writeFileSync(path.join(coverageDir, file), content);
       fs.unlinkSync(file);
     });
   }

   export default globalTeardown;
   ```

3. Use a separate Playwright configuration for coverage:

   Create a new Playwright config file specifically for coverage:

   ```typescript
   // playwright.coverage.config.ts
   import type { PlaywrightTestConfig } from '@playwright/test';

   const config: PlaywrightTestConfig = {
     use: {
       browserName: 'chromium',
       launchOptions: {
         args: ['--remote-debugging-port=9222'],
       },
     },
     reporter: [['json', { outputFile: 'test-results.json' }]],
   };

   export default config;
   ```

   Then run this configuration separately:

   ```yaml
   - name: Run tests
     run: npx playwright test --config=playwright.e2e.config.ts

   - name: Collect coverage
     run: npx playwright test --config=playwright.coverage.config.ts
   ```

4. Use a coverage collection tool like Istanbul:

   Install Istanbul:

   ```
   npm install --save-dev istanbul-lib-coverage istanbul-lib-report istanbul-reports
   ```

   Create a script to collect and report coverage:

   ```javascript
   // collect-coverage.js
   const libCoverage = require('istanbul-lib-coverage');
   const { createContext } = require('istanbul-lib-report');
   const reports = require('istanbul-reports');
   const fs = require('fs');

   const map = libCoverage.createCoverageMap();

   const coverageFiles = fs.readdirSync('.')
     .filter(file => file.endsWith('.coverage.json'));

   coverageFiles.forEach(file => {
     const coverage = JSON.parse(fs.readFileSync(file, 'utf8'));
     map.merge(coverage);
   });

   const context = createContext({
     dir: './coverage',
     coverageMap: map
   });

   reports.create('lcov').execute(context);
   reports.create('text').execute(context);
   ```

   Run this script after your tests complete.

Each of these approaches separates the coverage collection process from your main test run. Choose the one that best fits your project structure and CI pipeline. Would you like me to explain any of these options in more detail?

**Comment by doradsoft** [comment]
1. Good news, last bullet is done as well:
- [x] Merge coverage (https://www.npmjs.com/package/monocart-coverage-reports#merge-coverage-reports:~:text=and%20merging%20reports-,Manual%20Merging,-If%20the%20reports)

2. Regarding your last comment
3. In theory it might be something that we want, to separate test from coverage.
Practically:
a. In CI we always want both
b. If tests are failing coverage is not being calculated already
c. I thought before of adding an environment variable to control it and to have different npm scripts. Nice to have, no more then that.
d. the code you provided will 99% not work with nextjs, it is all what I was about the last period, of making use of nextjs-swc-jest-playwright-istanbul. Actually I wanted turbo as well but There is a bug which won't let me.

**Comment by HagegeR** [comment]
code cov report fixed
only missing the badge

**Comment by doradsoft** [comment]
Wow

> * Then /coverage/merged dir is generated with all relevant coverage data in two formats: html and raw.

apparently "raw" merging has some issue. Nonetheless you probasbly managed to overcome it differently.
Also now coverage:merge is generating final lines coverage percentage into coverage/merged/coverage-percentage.txt

**Comment by HagegeR** [comment]
this branch was already merged, don't you know how to open new branches? ;-)

I'll merge this with the change you suggested if it works.

do you have a codecov account ? if so I can provide you access

**Comment by doradsoft** [comment]
Well done @HagegeR
